# Generated by Django 4.0.4 on 2022-05-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_list', '0003_card_delete_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='color',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expansion',
        ),
        migrations.RemoveField(
            model_name='card',
            name='mana_cost',
        ),
        migrations.RemoveField(
            model_name='card',
            name='mana_value',
        ),
        migrations.RemoveField(
            model_name='card',
            name='rarity',
        ),
        migrations.AddField(
            model_name='card',
            name='card_condition',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
