# Generated by Django 4.0.4 on 2022-05-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_list', '0004_remove_card_card_type_remove_card_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
