# Generated by Django 4.0.4 on 2022-05-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_list', '0005_card_card_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_pic',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
