# Generated by Django 4.0.4 on 2022-05-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_list', '0006_alter_card_card_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='mana_value',
            field=models.IntegerField(default=0),
        ),
    ]
