# Generated by Django 4.0.4 on 2022-06-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_list', '0007_card_card_type_card_color_card_mana_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expansion_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
