# Generated by Django 4.0.4 on 2022-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_list', '0008_card_expansion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
