# Generated by Django 4.0.4 on 2022-06-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_list', '0010_card_price_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='effect',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
