# Generated by Django 4.0.4 on 2022-06-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_list', '0011_alter_card_effect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='price_updated',
        ),
    ]
